### ISSUE TITLE
"It also contains a functional for"

### ISSUE THREAD

**Issue by wallymathieu** [AlexTroshkin/fsharp-dapper#14]
Perhaps what is meant is "functional approach" ?

I.e. that the project description should be:
"The wrapper above the 'Dapper' library allows you to write more familiar code in the F # language. It also contains a functional approach for more simple work with temporary tables"
?

**Comment by AlexTroshkin** [comment]
Hello @wallymathieu 

I did not mean the functional approach
Here, additional functionality was implied, which is missing from Dapper.

**Comment by wallymathieu** [comment]
Aaa, thanks! That makes me less confused. 😄
